services:
  neo4j:
    image: graphstack/dozerdb:5.26.3.0
    container_name: ai-catalog-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_dbms_security_procedures_unrestricted: '*'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      # Memory and performance settings for development
      NEO4J_dbms_memory_heap_initial__size: '1G'
      NEO4J_dbms_memory_heap_max__size: '2G'
      NEO4J_dbms_memory_pagecache_size: '512M'
      # Reduce startup time
      NEO4J_dbms_logs_gc_enabled: 'false'
      NEO4J_dbms_jvm_additional: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    # Ensure clean shutdown
    stop_grace_period: 30s

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: